### ISSUE TITLE
Ch. 5.4 Appendix D: There are strings "###" that should be revised.

### ISSUE THREAD

**Issue by jmaferreira** [DILCISBoard/E-ARK-SIP#22] opened 2019-03-06 11:12 UTC

**Comment by jmaferreira** [comment] 2019-03-13 15:34
I believe this has to do with the PDF generator. Carl, can you take a look at this issue?

My editor

![Screenshot 2019-03-13 at 15 33 23](https://user-images.githubusercontent.com/3181302/54292083-7b2d5680-45a5-11e9-91a7-040687ad5ee2.png)

On the generated PDF:

<img width="788" alt="Screenshot 2019-03-13 at 15 33 29" src="https://user-images.githubusercontent.com/3181302/54292094-7f597400-45a5-11e9-8eab-9311c3a81161.png">

**Comment by jmaferreira** [comment] 2019-05-13 13:30
@carlwilson Please take notice of this issue when generating the final versions of the PDFs.

**Comment by carlwilson** [comment] 2019-05-14 13:01
I'm pretty sure I know the cause now. We're altering this section anyway and I'll make sure that it's fixed for the PDF issued 15/05

**Comment by carlwilson** [comment] 2019-05-15 02:47
Fixed by DILCISBoard/E-ARK-CSIP#510

**Comment by carlwilson** [comment] 2019-09-14 23:12
Fixed in v2.0.1

**Comment by karinbredenberg** [comment] 2020-01-14 11:58
The ### has been removed with the version 2.0.1.

**Closed by karinbredenberg** 2020-01-14 11:58 UTC
Labels: DILCIS review, bug, ready
