### ISSUE TITLE
SIP32

### ISSUE THREAD

**Issue by karinbredenberg** [DILCISBoard/E-ARK-SIP#37] opened 2019-04-29 13:02 UTC
Comment left in a mail to info@dilcis.eu

SIP32: content repetition “Follows the requirements in the CSIP profile. Follows the requirements in the CSIP profile.”

**Comment by jmaferreira** [comment] 2019-05-13 14:06
Its a problem with the auto generator.
I've fixed it temporarily with a dummy id.

Related to #24

**Comment by carlwilson** [comment] 2019-05-14 13:17
This is a duplicate of #24 in effect. I need to clear the text buffer more systematically but I've requested a little feedback at #24

**Closed** 2020-04-30 15:28 UTC
Labels: bug
