### ISSUE TITLE
Link to extension schema

### ISSUE THREAD

**Issue by karinbredenberg** [DILCISBoard/E-ARK-SIP#39] opened 2019-04-29 13:04 UTC
Comment left in a mail to info@dilcis.eu

 Link https://dilcis.eu/XML/METS/SIPExtensionMETS/SIPExtensionMETS.xsd does not work

**Comment by jmaferreira** [comment] 2019-05-13 13:44
This is a tricky one as it comes with several problems:

1. The issue is located on the E-ARK-SIP.xml (i.e. the SIP METS profile).
2. The referred namespace doesn't have to be published on the cited URL, however, it is always nice to find it where it is supposed to be, so my recommendation is to put it on the DILCIS Board website.
3. The version number should be on the URL path or on the filename as different version of the spec might use different METS profiles
4. The only XSD we have on the SIP project is the https://github.com/DILCISBoard/E-ARK-SIP/blob/master/schema/DILCISExtensionSIPMETS.xsd which has a different name than SIPExtensionMETS.xsd. So this should be fixed as well on either side.

**Comment by karinbredenberg** [comment] 2019-05-13 15:15
Also needs the help of @carlwilson

**Comment by karinbredenberg** [comment] 2019-09-03 14:04
The link in the profile to the schema: https://dilcis.eu/XML/METS/SIPExtensionMETS/DILCISExtensionSIPMETS.xsd isnt working the path should be http://earksip.dilcis.eu/schema/ ???? Also when the reference to the schema is made in xsi:SchemaLocation @carlwilson

**Comment by karinbredenberg** [comment] 2019-10-28 16:18
Fixed with PR #67

**Closed** 2019-10-28 16:28 UTC
